version: '2'
services:
  # Shared Services - message queues, databases, etc.
  rabbitMQ:
    container_name: shared-rabbitMQ
    image: rabbitmq:3.6.5-management
    hostname: my-rabbit
    ports:
      # - 5672:5672
      - 15673:15672

  mongoDB:
    container_name: shared-mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  postgresDB:
    container_name: shared-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: AfiniDB400
    volumes:
      - ./data/postgres:/var/lib/postresql/data

  neo4jDB:
    container_name: shared-neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none
    volumes:
      - ./data/neo4j:/data

  redis:
    container_name: shared-redis
    image: redis:latest
    ports:
      - 6379:6379

  #Sites
  web-public:
    container_name: web-public
    image: afiniclub/web-public
    environment:
      NODE_ENV:
    ports:
      - 9000:9000
    command: npm run webserver -p 9000:9000

  web-member:
    container_name: web-member
    image: afiniclub/web-member
    environment:
      NODE_ENV:
    ports:
      - 9001:9001
    command: npm run webserver -p 9001:9001

  web-admin:
    container_name: web-admin
    image: afiniclub/web-admin
    environment:
      NODE_ENV:
    ports:
      - 9003:9003
    command: npm run webserver -p 9003:9003

  #APIs
  afini-billing-api:
    container_name: billing-api
    image: afiniclub/billing-api
    environment:
      NODE_ENV:
    ports:
      - 3000:3000
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-contact-info-api:
    container_name: contact-info-api
    image: afiniclub/contact-info-api
    environment:
      NODE_ENV:
    ports:
      - 3012:3012
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-membership-account-api:
    container_name: mem-acct-api
    image: afiniclub/mem-acct-api
    environment:
      NODE_ENV:
    ports:
      - 3001:3000
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-note-api:
    container_name: note-api
    image: afiniclub/note-api
    environment:
      NODE_ENV:
    ports:
      - 3008:3008
    links:
      - mongoDB:docker-mongo
    depends_on:
      - mongoDB

  # afini-payment-api:
  #   container_name: payment-api
  #   image: afiniclub/payment-api
  #   environment:
  #     NODE_ENV:
  #   ports:
  #     - 3002:3002
  #   links:
  #     - mongoDB:docker-mongo
  #   depends_on:
  #     - mongoDB

  afini-pricing-api:
    container_name: pricing-api
    image: afiniclub/pricing-api
    environment:
      NODE_ENV:
    ports:
      - 3009:3009
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
      - postgresDB:docker-postgres
    depends_on:
      - rabbitMQ
      - mongoDB
      - postgresDB

  afini-itops-api:
    container_name: itops-api
    image: afiniclub/itops-api
    environment:
      NODE_ENV:
    ports:
      - 3015:3015
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-residence-api:
    container_name: residence-api
    image: afiniclub/residence-api
    environment:
      NODE_ENV: test
    ports:
      - 3010:3010
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
      - neo4jDB:docker-neo4j
    depends_on:
      - rabbitMQ
      - mongoDB
      - neo4jDB

  afini-reservation-api:
    container_name: reservation-api
    image: afiniclub/reservation-api
    environment:
      NODE_ENV:
    ports:
      - 3006:3006
    links:
      - mongoDB:docker-mongo
      - rabbitMQ:docker-rabbitmq
    depends_on:
      - mongoDB
      - rabbitMQ

  afini-user-api:
    container_name: user-api
    image: afiniclub/user-api
    environment:
      NODE_ENV:
    ports:
      - 3005:3005
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-messaging-api:
    container_name: messaging-api
    image: afiniclub/messaging-api
    environment:
      NODE_ENV:
    ports:
      - 3013:3013
    links:
      - mongoDB:docker-mongo
    depends_on:
      - mongoDB

  afini-trip-api:
    container_name: trip-api
    image: afiniclub/trip-api
    environment:
      NODE_ENV:
    ports:
      - 3014:3014
    links:
      - mongoDB:docker-mongo
    depends_on:
      - mongoDB

  afini-external-residences-api:
    container_name: ext-residence-api
    image: afiniclub/ext-residence-api
    environment:
      NODE_ENV:
    ports:
      - 3016:3016
    links:
      - mongoDB:docker-mongo
      - postgresDB:docker-postgres
    depends_on:
      - mongoDB
      - postgresDB

  #Services (RabbitMQ Handlers)
  afini-contact-info-service:
    container_name: contact-info-svc
    image: afiniclub/contact-info-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-itops-service:
    container_name: itops-svc
    image: afiniclub/itops-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-itops-cache-service:
    container_name: itops-cache-svc
    image: afiniclub/itops-cache-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
      - redis:docker-redis
    depends_on:
      - rabbitMQ
      - mongoDB
      - redis

  afini-membership-account-service:
    container_name: mem-acct-svc
    image: afiniclub/mem-acct-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-note-service:
    container_name: note-svc
    image: afiniclub/note-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-pricing-service:
    container_name: pricing-svc
    image: afiniclub/pricing-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-pricing-cache-service:
    container_name: pricing-cache-svc
    image: afiniclub/pricing-cache-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - postgresDB:docker-postgres
    depends_on:
      - rabbitMQ
      - postgresDB

  afini-reservation-service:
    container_name: reservation-svc
    image: afiniclub/reservation-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  # afini-user-service:
  #   container_name: user-svc
  #   #image: afiniclub/user-svc
  #   volumes:
  #     - ../../afini-user-rmqhandler:/usr/src/app
  #   build: ../../afini-user-rmqhandler
  #   environment:
  #     NODE_ENV:
  #   links:
  #     - rabbitMQ:docker-rabbitmq
  #     - mongoDB:docker-mongo
  #   depends_on:
  #     - rabbitMQ
  #     - mongoDB

  afini-messaging-service:
    container_name: messaging-svc
    image: afiniclub/messaging-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-residence-service:
    container_name: residence-svc
    image: afiniclub/residence-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
      - neo4jDB:docker-neo4j
    depends_on:
      - rabbitMQ
      - mongoDB
      - neo4jDB

  afini-ext-residence-service:
    container_name: ext-residence-svc
    image: afiniclub/ext-residence-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - postgresDB:docker-postgres
    depends_on:
      - rabbitMQ
      - postgresDB

  afini-audit-service:
    container_name: audit-svc
    image: afiniclub/audit-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-billing-service:
    container_name: billing-svc
    image: afiniclub/billing-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB

  afini-trip-service:
    container_name: trip-svc
    image: afiniclub/trip-svc
    environment:
      NODE_ENV:
    links:
      - rabbitMQ:docker-rabbitmq
      - mongoDB:docker-mongo
    depends_on:
      - rabbitMQ
      - mongoDB
